- name: install lazygit-0.50.0
  hosts: localhost 
  become: true
  tasks:
    - name: create lazygit directory in /opt location
      ansible.builtin.file:
        path: /opt/lazygit
        state: directory
        mode: '0755'

    - name: curl lazygit binary files
      ansible.builtin.uri:
        url: https://github.com/jesseduffield/lazygit/releases/download/v0.50.0/lazygit_0.50.0_Linux_x86_64.tar.gz
        dest: /opt/lazygit/lazygit_0.50.0_Linux_x86_64.tar.gz

    - name: extract lazy git tar.gz file
      ansible.builtin.unarchive:
        owner: root
        group: root
        mode: '0755'
        src: /opt/lazygit/lazygit_0.50.0_Linux_x86_64.tar.gz
        dest: /opt/lazygit

    - name: create lazygit symbolic link
      ansible.builtin.file:
        src: /opt/lazygit/lazygit
        dest: /usr/bin/lazygit
        owner: root
        group: root
        state: link

