- name: install vscode
  hosts: localhost 
  become: true
  tasks:
    - name: install wget, gpg
      ansible.builtin.apt:
        name:
          - wget
          - gpg
        state: present
        update_cache: true

    - name: get vscode url gpg key
      ansible.builtin.shell: | 
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc \
        | gpg --dearmor > /etc/apt/keyrings/vscode.gpg
      args:
        creates: /etc/apt/keyrings/vscode.gpg

    - name: Change permissions to gpg key file
      ansible.builtin.file:
        path: /etc/apt/keyrings/vscode.gpg
        owner: root
        group: root
        mode: '0644'

    - name: Set DPKG architecture
      ansible.builtin.set_fact:
        dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

    - debug:
        msg: "{{ dpkg_arch }}"

    - name: add vscode repository 
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ dpkg_arch }} signed-by=/etc/apt/keyrings/vscode.gpg] https://packages.microsoft.com/repos/code stable main"
        state: present
        filename: vscode
        update_cache: true

    - name: install apt-transport-https
      ansible.builtin.apt:
        name: apt-transport-https
        update_cache: true

    - name: install vscode
      ansible.builtin.apt:
        name: code
        update_cache: true
